# Generated by Django 5.2.7 on 2025-10-14 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mots_cles', models.CharField(help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contenus/')),
                ('type_contenu', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('texte', 'Texte')], default='pdf', max_length=10)),
                ('matiere', models.CharField(max_length=100)),
                ('universite', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
