# Generated by Django 5.1.3 on 2025-10-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telechargement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='supprime',
            field=models.BooleanField(default=False, help_text='Indique si le fichier a été supprimé logiquement.'),
        ),
    ]
