# Generated by Django 5.2.7 on 2025-10-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telechargement', '0002_fichier_supprime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='supprime',
        ),
    ]
