# Generated by Django 5.2.7 on 2025-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
