# Generated by Django 5.2.7 on 2025-10-22 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu publié', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du contenu')),
                ('mots_cles', models.CharField(help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('fichier', models.FileField(blank=True, help_text='Fichier à publier', null=True, upload_to='publications/')),
                ('type_contenu', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('texte', 'Texte'), ('image', 'Image'), ('presentation', 'Présentation')], default='pdf', help_text='Type de contenu', max_length=15)),
                ('matiere', models.CharField(help_text='Matière ou cours', max_length=100)),
                ('universite', models.CharField(help_text='Université ou établissement', max_length=100)),
                ('theme', models.CharField(help_text='Thème ou sujet', max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True, help_text='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('est_publie', models.BooleanField(default=True, help_text='Statut de publication')),
                ('auteur', models.ForeignKey(help_text='Auteur de la publication', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
    ]
