# Generated by Django 4.2.11 on 2025-10-27 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mots_cles', models.CharField(blank=True, max_length=500)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('type_contenu', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('texte', 'Texte'), ('image', 'Image'), ('presentation', 'Présentation')], default='pdf', max_length=15)),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('universite', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-date_publication'],
            },
        ),
    ]
