# Generated by Django 5.2.7 on 2025-11-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
